write:
  # -- Number of replicas for the write
  replicas: 3
  extraEnvFrom:
    - secretRef:
        name: loki-secrets
  extraArgs:
  - -config.expand-env=true
read:
  # -- Number of replicas for the read
  replicas: 3
  extraEnvFrom:
    - secretRef:
        name: loki-secrets
  extraArgs:
  - -config.expand-env=true
  autoscaling:
    # -- Enable autoscaling for the read, this is only used if `queryIndex.enabled: true`
    enabled: true
    # -- Minimum autoscaling replicas for the read
    minReplicas: 3
    # -- Maximum autoscaling replicas for the read
    maxReplicas: 9
loki:
  config:
    limits_config:
      ingestion_burst_size_mb: 16
      ingestion_rate_mb: 16
      max_streams_per_user: 100000
    common:
      storage:
        filesystem: null
        azure:
          # For the account-key, see docs: https://docs.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal
          account_key: ${AZURE_ACCOUNT_KEY}
          # Your azure account name
          account_name: storeme
          # See https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction#containers
          container_name: loki
          request_timeout: 0
    schema_config:
      configs:
        - from: "2020-12-11"
          store: boltdb-shipper
          object_store: azure
          schema: v11
          index:
            period: 24h
            prefix: loki_index_
gateway:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: loki-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - promtail'
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: loki.aks.cookingwithazure.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: loki.aks.cookingwithazure.com
        hosts:
          - loki.aks.cookingwithazure.com